### ISSUE TITLE
Deployment failure report

### ISSUE THREAD

**Issue by johndmulhausen** [GoogleCloudPlatform/appengine-websocketchat-java#3]
Passing on some doc feedback we got:
----
Guys. I've used GAE for a couple of years. I just went to https://github.com/GoogleCloudPlatform/appengine-websocketchat-java and tried to upload it, but its actually out of date, and badly needs an upgrade - from you.

Can you please do this ?
The error I see is just before deployment would succeed:
99% Error Create Config Bucket failed. during VmCreateConfigBucket. Deployed Version: chat.384021930865687675

**Comment by ludoch** [comment]
I'll see what we can do...
Ludo

**Comment by ludoch** [comment]
Fix. using the latest Cloud SDK Maven plugin.
